--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

-- Started on 2023-01-12 12:44:24

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--DROP DATABASE "BasicCrud";
--
-- TOC entry 3331 (class 1262 OID 16410)
-- Name: BasicCrud; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "BasicCrud" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Turkish_Turkey.1254';


ALTER DATABASE "BasicCrud" OWNER TO postgres;

--connect "BasicCrud"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16417)
-- Name: Products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Products" (
    "Id" integer NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Stock" integer NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedDate" timestamp with time zone NOT NULL
);


ALTER TABLE public."Products" OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16416)
-- Name: Products_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Products" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Products_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16411)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3325 (class 0 OID 16417)
-- Dependencies: 216
-- Data for Name: Products; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Products" ("Id", "Name", "Stock", "Price", "CreatedDate", "ModifiedDate") VALUES (1, 'Bilgisayar', 10, 44899.00, '2023-01-12 11:19:57.337559+03', '2023-01-12 11:19:57.337597+03');
INSERT INTO public."Products" ("Id", "Name", "Stock", "Price", "CreatedDate", "ModifiedDate") VALUES (3, 'Mouse', 70, 199.99, '2023-01-12 11:20:21.894906+03', '2023-01-12 11:20:21.894906+03');
INSERT INTO public."Products" ("Id", "Name", "Stock", "Price", "CreatedDate", "ModifiedDate") VALUES (2, 'Klavye', 10, 256.99, '2023-01-12 11:20:10.898044+03', '2023-01-12 11:20:59.842201+03');


--
-- TOC entry 3323 (class 0 OID 16411)
-- Dependencies: 214
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20230112080159_InitialCreate', '7.0.2');


--
-- TOC entry 3332 (class 0 OID 0)
-- Dependencies: 215
-- Name: Products_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Products_Id_seq"', 10, true);


--
-- TOC entry 3180 (class 2606 OID 16421)
-- Name: Products PK_Products; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "PK_Products" PRIMARY KEY ("Id");


--
-- TOC entry 3178 (class 2606 OID 16415)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


-- Completed on 2023-01-12 12:44:24

--
-- PostgreSQL database dump complete
--

